export const ADD_TODO = "ADD_TODO";
export const DEL_TODO = "DEL_TODO";
export const TOGGLE_TODO = "TOGGLE_TODO";
export const EDIT_TODO = "EDIT_TODO";



export const ADD_TODO_LOADING = "ADD_TODO_LOADING";
export const ADD_TODO_SUCCESS = "ADD_TODO_SUCCESS";
export const ADD_TODO_ERROR = "ADD_TODO_ERROR";

export const GET_TODO_LOADING = "GET_TODO_LOADING";
export const GET_TODO_SUCCESS = "GET_TODO_SUCCESS";
export const GET_TODO_ERROR = "GET_TODO_ERROR";

export const DEL_TODO_LOADING = "DEL_TODO_LOADING";
export const DEL_TODO_SUCCESS = "DEL_TODO_SUCCESS";
export const DEL_TODO_ERROR = "DEL_TODO_ERROR";

export const TOGGLE_TODO_LOADING = "TOGGLE_TODO_LOADING";
export const TOGGLE_TODO_SUCCESS = "TOGGLE_TODO_SUCCESS";
export const TOGGLE_TODO_ERROR = "TOGGLE_TODO_ERROR";

export const EDIT_TODO_LOADING = "EDIT_TODO_LOADING";
export const EDIT_TODO_SUCCESS = "EDIT_TODO_SUCCESS";
export const EDIT_TODO_ERROR = "EDIT_TODO_ERROR";